CREATE DATABASE HOTEL;
USE HOTEL;

CREATE TABLE 'RESERVATION'(
'ID' int NOT NULL AUTO_INCREMENT,
'USERNAME' varchar(20) NOT NULL DEFAULT '',
'BONUSPOINT' BIGING NOT NULL DEFAULT 0,
'ROOMNO' int NOT NULL DEFAULT 0,
'PRICE' int NOT NULL DEFAULT 0,
'STATUS' varchar(20) NOT NULL DEFAULT '',
'DATE' timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP);


insert into 'RESERVATION'
VALUES(1,'ABC',200,100,2000,'BOOKED',NOW());